spring.application.name=Транспорт
spring.main.banner-mode=off
spring.main.log-startup-info=false

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vehicle_lab}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true

spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
server.port=${SERVER_PORT:6767}

spring.messages.basename=messages
spring.messages.encoding=UTF-8
