CREATE TABLE coordinates (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
 coordinate_x DOUBLE PRECISION NOT NULL CHECK (coordinate_x BETWEEN -1.7976931348623157E308 AND 1.7976931348623157E308),
 coordinate_y REAL NOT NULL CHECK (coordinate_y BETWEEN -3.4028235E38 AND 408)
);
INSERT INTO coordinates (id,coordinate_x,coordinate_y) SELECT id,coordinate_x,coordinate_y FROM vehicles;
SELECT setval(pg_get_serial_sequence('coordinates','id'), COALESCE((SELECT MAX(id) FROM coordinates),1), EXISTS(SELECT 1 FROM coordinates));
ALTER TABLE vehicles ADD COLUMN coordinates_id INTEGER;
UPDATE vehicles SET coordinates_id=id;
ALTER TABLE vehicles ALTER COLUMN coordinates_id SET NOT NULL;
ALTER TABLE vehicles ADD CONSTRAINT fk_vehicle_coordinates FOREIGN KEY (coordinates_id) REFERENCES coordinates(id) ON DELETE RESTRICT;
ALTER TABLE vehicles DROP COLUMN coordinate_x, DROP COLUMN coordinate_y;
ALTER TABLE vehicles ADD CONSTRAINT ck_vehicle_capacity_finite CHECK (capacity BETWEEN 0 AND 1.7976931348623157E308);
ALTER TABLE vehicles ADD CONSTRAINT ck_vehicle_consumption_finite CHECK (fuel_consumption BETWEEN 0 AND 1.7976931348623157E308);
CREATE INDEX idx_vehicle_coordinates ON vehicles(coordinates_id);
