CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password_hash VARCHAR(60) NOT NULL,
    CONSTRAINT valid_username CHECK (username ~ '^[a-z0-9_]{3,32}$'),
    CONSTRAINT valid_password_hash CHECK (char_length(password_hash) = 60)
);

CREATE TABLE app_seed_state (
    name VARCHAR(64) PRIMARY KEY
);

UPDATE vehicles SET name = replace(replace(name, chr(8212), '-'), chr(8211), '-');
